name: portfolio
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icons/

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro/SourceSansPro-Black.ttf
          weight: 700
        - asset: fonts/SourceSansPro/SourceSansPro-Bold.ttf
          weight: 600
        - asset: fonts/SourceSansPro/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro/SourceSansPro-Light.ttf
          weight: 100
    - family: Crillee Italic Std
      fonts:
        - asset: fonts/CrilleeItalicStd/CrilleeItalicStdRegular.otf